# Usa la imagen oficial de PHP con Apache
FROM php:8.2-apache
# Copia el archivo PHP al directorio raíz del servidor web
COPY index.php /var/www/html/
# Documentamos para los lectores del Dockerfile en que puerto se lanza la app
EXPOSE 80
